# Nombre de la aplicacion
spring.application.name=sistema-control-sanitario-ganado

# Exponer el endpoint de health de Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
