spring.datasource.url=jdbc:postgresql://localhost:5432/ganado_db
spring.datasource.username=ganado_user
spring.datasource.password=ganado_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.data.mongodb.uri=mongodb://localhost:27017/ganado_auditoria
spring.data.mongodb.database=ganado_auditoria
spring.autoconfigure.exclude=

server.port=8080
